# Indian Air Quality Intelligence Platform

## Notebook 01 – Data Loading

### Objectives

- Load the raw dataset
- Verify successful loading
- Inspect the dataset structure
- Record basic dataset statistics

In [2]:
import warnings
warnings.filterwarnings("ignore")

import os
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

In [16]:
from pathlib import Path

DATA_PATH = Path("../data/raw/INDIA_AQI_COMPLETE_20251126.csv")

if not DATA_PATH.exists():
    raise FileNotFoundError(f"{DATA_PATH} not found.")

In [17]:
df = pd.read_csv(DATA_PATH)

In [5]:
print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [20]:
print("=" * 50)
print("DATASET SUMMARY")
print("=" * 50)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

==================================================
DATASET SUMMARY
==================================================
Rows    : 842,160
Columns : 71

In [7]:
df.head()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,Day_Name,Week_of_Year,Is_Weekend,Quarter,Season,Time_of_Day,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.83,91.29,2022-08-05 00:00:00,2022,8,5,0,4,Friday,31,0,3,Monsoon,Night,26.70,NaN,NaN,NaN,91,25.10,Very_Humid,5.40,NaN,NaN,172,11.20,Moderate,0,0.00,0.00,0,0,1004.40,1003.00,0.00,0.00,0.00,NaN,100,0,7,100,0,0.00,14.80,21.50,0.69,197.00,21.80,2.70,32.00,0.00,NaN,0.14,NaN,NaN,NaN,11.00,16.00,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.83,91.29,2022-08-05 01:00:00,2022,8,5,1,4,Friday,31,0,3,Monsoon,Night,26.40,NaN,NaN,NaN,93,25.20,Very_Humid,4.50,NaN,NaN,166,9.00,Light,0,0.00,0.00,0,0,1003.90,1002.50,0.00,0.00,0.00,NaN,100,3,4,100,0,0.00,15.70,22.80,0.69,196.00,18.50,3.00,33.00,0.00,NaN,0.14,NaN,NaN,NaN,9.00,14.00,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.83,91.29,2022-08-05 02:00:00,2022,8,5,2,4,Friday,31,0,3,Monsoon,Night,26.10,NaN,NaN,NaN,95,25.20,Very_Humid,3.80,NaN,NaN,163,7.60,Light,0,0.00,0.00,0,0,1003.50,1002.10,0.00,0.00,0.00,NaN,100,2,2,100,0,0.00,16.30,23.50,0.69,196.00,15.10,3.30,34.00,0.00,NaN,0.15,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.83,91.29,2022-08-05 03:00:00,2022,8,5,3,4,Friday,31,0,3,Monsoon,Night,26.00,NaN,NaN,NaN,96,25.20,Very_Humid,3.70,NaN,NaN,151,6.80,Light,0,0.00,0.00,0,0,1003.00,1001.60,0.00,0.00,0.00,NaN,100,0,1,100,0,0.00,17.60,25.40,0.69,197.00,14.10,3.30,32.00,0.00,NaN,0.15,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.83,91.29,2022-08-05 04:00:00,2022,8,5,4,4,Friday,31,0,3,Monsoon,Night,25.80,NaN,NaN,NaN,97,25.20,Very_Humid,4.10,NaN,NaN,128,6.80,Light,0,0.00,0.00,0,0,1002.90,1001.50,0.00,0.00,0.00,NaN,100,0,1,100,0,0.00,18.20,26.20,0.69,199.00,13.90,3.20,30.00,0.00,NaN,0.14,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [8]:
df.sample(10, random_state=42)

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,Day_Name,Week_of_Year,Is_Weekend,Quarter,Season,Time_of_Day,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
160063,Bhubaneswar,Odisha,20.30,85.82,2024-04-15 07:00:00,2024,4,15,7,0,Monday,16,0,2,Summer,Early_Morning,29.30,NaN,NaN,NaN,61,21.00,Comfortable,1.10,NaN,NaN,198,7.90,Calm,1,0.00,0.00,0,0,1011.60,1006.60,248.00,155.00,93.00,NaN,0,0,0,0,1,3600.00,37.30,58.10,0.64,408.00,5.40,9.50,91.00,2.00,NaN,0.63,111.00,111.00,54.00,3.00,36.00,4,72.00,72.00,65.00,Unhealthy_Sensitive,Satisfactory,0,NaN,0,0
541575,Kolkata,West Bengal,22.57,88.36,2024-09-28 15:00:00,2024,9,28,15,5,Saturday,39,1,3,Monsoon,Afternoon,30.60,NaN,NaN,NaN,74,25.40,Humid,15.60,NaN,NaN,204,33.50,Fresh,0,0.20,0.20,1,0,1005.70,1004.30,342.00,204.00,138.00,NaN,95,22,19,92,1,3600.00,8.20,13.10,0.63,164.00,5.10,4.60,62.00,0.00,NaN,0.24,40.00,40.00,14.00,3.00,32.00,2,25.00,19.00,16.00,Good,Good,0,NaN,0,0
322601,Gurugram,Haryana,28.46,77.03,2022-12-14 17:00:00,2022,12,14,17,2,Wednesday,50,0,4,Winter,Afternoon,17.10,NaN,NaN,NaN,48,5.90,Dry,9.00,NaN,NaN,299,18.40,Moderate,0,0.00,0.00,0,0,1015.10,988.30,41.00,15.00,26.00,NaN,0,0,0,0,0,954.22,0.50,0.70,0.71,59.00,0.00,0.80,27.00,0.00,NaN,0.05,14.00,3.00,1.00,0.00,14.00,1,11.00,1.00,1.00,Good,Good,0,NaN,0,0
794503,Thiruvananthapuram,Kerala,8.52,76.94,2023-10-13 07:00:00,2023,10,13,7,4,Friday,41,0,4,Post_Monsoon,Early_Morning,25.20,NaN,NaN,NaN,93,24.00,Very_Humid,1.00,NaN,NaN,135,9.40,Calm,1,0.00,0.00,0,0,1013.10,1011.70,128.00,75.00,53.00,NaN,5,2,0,3,1,3578.26,8.50,13.30,0.64,194.00,6.70,3.20,46.00,0.00,NaN,0.43,24.00,24.00,9.00,3.00,19.00,2,18.00,12.00,10.00,Good,Good,0,NaN,0,1
483702,Jaipur,Rajasthan,26.91,75.79,2024-10-07 06:00:00,2024,10,7,6,0,Monday,41,0,4,Post_Monsoon,Early_Morning,22.50,NaN,NaN,NaN,80,18.80,Humid,6.00,NaN,NaN,353,10.40,Moderate,0,0.00,0.00,0,0,1014.30,965.30,0.00,0.00,0.00,NaN,0,0,0,0,1,0.00,26.60,51.00,0.52,421.00,22.60,8.80,37.00,32.00,NaN,0.25,78.00,78.00,46.00,11.00,15.00,5,60.00,60.00,60.00,Moderate,Good,0,NaN,0,1
64165,Aizawl,Mizoram,23.73,92.72,2023-04-15 13:00:00,2023,4,15,13,5,Saturday,15,1,2,Summer,Afternoon,32.10,NaN,NaN,NaN,20,6.20,Very_Dry,11.50,NaN,NaN,321,36.40,Fresh,0,0.00,0.00,0,0,1007.50,895.10,824.00,623.00,201.00,NaN,100,0,0,100,1,3600.00,25.10,36.40,0.69,289.00,0.70,7.00,171.00,1.00,NaN,0.57,90.00,74.00,30.00,0.00,90.00,3,67.00,52.00,33.00,Moderate,Good,0,NaN,0,0
817902,Visakhapatnam,Andhra Pradesh,17.69,83.22,2023-02-20 06:00:00,2023,2,20,6,0,Monday,8,0,1,Winter,Early_Morning,20.90,NaN,NaN,NaN,97,20.40,Very_Humid,5.40,NaN,NaN,356,7.20,Moderate,0,0.00,0.00,0,0,1013.50,1008.80,0.00,0.00,0.00,NaN,7,7,1,0,1,0.00,89.90,131.30,0.68,1665.00,38.80,70.60,35.00,1.00,NaN,0.95,131.00,131.00,59.00,19.00,17.00,17,78.00,78.00,69.00,Unhealthy_Sensitive,Moderate,0,NaN,0,0
118128,Bhopal,Madhya Pradesh,23.26,77.41,2022-10-26 00:00:00,2022,10,26,0,2,Wednesday,43,0,4,Post_Monsoon,Night,20.50,NaN,NaN,NaN,53,10.70,Comfortable,7.10,NaN,NaN,15,13.00,Moderate,0,0.00,0.00,0,0,1012.90,956.50,0.00,0.00,0.00,NaN,0,0,0,0,0,0.00,68.20,100.10,0.68,675.00,28.60,8.60,51.00,9.00,NaN,0.42,141.00,141.00,61.00,14.00,33.00,5,82.00,82.00,71.00,Unhealthy_Sensitive,Moderate,0,NaN,1,1
503077,Kohima,Nagaland,25.68,94.11,2023-08-31 13:00:00,2023,8,31,13,3,Thursday,35,0,3,Monsoon,Afternoon,25.50,NaN,NaN,NaN,74,20.60,Humid,6.40,NaN,NaN,27,22.00,Moderate,0,0.10,0.10,1,0,1006.80,856.20,672.00,397.00,275.00,NaN,100,100,22,71,1,3600.00,24.90,41.40,0.60,213.00,0.60,0.90,104.00,31.00,NaN,0.51,72.00,72.00,33.00,0.00,39.00,2,50.00,50.00,36.00,Moderate,Good,0,NaN,0,0
703657,Ranchi,Jharkhand,23.34,85.31,2023-05-11 01:00:00,2023,5,11,1,3,Thursday,19,0,2,Summer,Night,24.70,NaN,NaN,NaN,20,0.30,Very_Dry,8.40,NaN,NaN,329,13.70,Moderate,0,0.00,0.00,0,0,1007.40,936.50,0.00,0.00,0.00,NaN,0,0,0,0,0,0.00,26.40,38.00,0.69,334.00,22.30,19.90,81.00,1.00,NaN,0.27,83.00,83.00,37.00,11.00,57.00,3,62.00,62.00,41.00,Moderate,Good,0,NaN,0,0

In [9]:
df.shape

(842160, 71)

In [10]:
df.columns.tolist()

['City',
 'State',
 'Latitude',
 'Longitude',
 'Datetime',
 'Year',
 'Month',
 'Day',
 'Hour',
 'Day_of_Week',
 'Day_Name',
 'Week_of_Year',
 'Is_Weekend',
 'Quarter',
 'Season',
 'Time_of_Day',
 'Temp_2m_C',
 'Temp_80m_C',
 'Temp_120m_C',
 'Temp_180m_C',
 'Humidity_Percent',
 'Dew_Point_C',
 'Humidity_Category',
 'Wind_Speed_10m_kmh',
 'Wind_Speed_80m_kmh',
 'Wind_Speed_120m_kmh',
 'Wind_Dir_10m',
 'Wind_Gusts_kmh',
 'Wind_Category',
 'Wind_Stagnation',
 'Precipitation_mm',
 'Rain_mm',
 'Is_Raining',
 'Heavy_Rain',
 'Pressure_MSL_hPa',
 'Surface_Pressure_hPa',
 'Solar_Radiation_Wm2',
 'Direct_Radiation_Wm2',
 'Diffuse_Radiation_Wm2',
 'UV_Index',
 'Cloud_Cover_Percent',
 'Cloud_Low_Percent',
 'Cloud_Mid_Percent',
 'Cloud_High_Percent',
 'Is_Daytime',
 'Sunshine_Seconds',
 'PM2_5_ugm3',
 'PM10_ugm3',
 'PM_Ratio',
 'CO_ugm3',
 'NO2_ugm3',
 'SO2_ugm3',
 'O3_ugm3',
 'Dust_ugm3',
 'NH3_ugm3',
 'AOD',
 'US_AQI',
 'US_AQI_PM25',
 'US_AQI_PM10',
 'US_AQI_NO2',
 'US_AQI_O3',
 'US_AQI_CO',
 'EU_AQI',
 'EU_AQI_PM25',
 'EU_AQI_PM10',
 'AQI_Category',
 'PM25_Category_India',
 'Temp_Inversion',
 'Inversion_Strength_C',
 'Festival_Period',
 'Crop_Burning_Season']

In [11]:
df.dtypes

City                      object
State                     object
Latitude                 float64
Longitude                float64
Datetime                  object
Year                       int64
Month                      int64
Day                        int64
Hour                       int64
Day_of_Week                int64
Day_Name                  object
Week_of_Year               int64
Is_Weekend                 int64
Quarter                    int64
Season                    object
Time_of_Day               object
Temp_2m_C                float64
Temp_80m_C               float64
Temp_120m_C              float64
Temp_180m_C              float64
Humidity_Percent           int64
Dew_Point_C              float64
Humidity_Category         object
Wind_Speed_10m_kmh       float64
Wind_Speed_80m_kmh       float64
Wind_Speed_120m_kmh      float64
Wind_Dir_10m               int64
Wind_Gusts_kmh           float64
Wind_Category             object
Wind_Stagnation            int64
Precipitation_mm         float64
Rain_mm                  float64
Is_Raining                 int64
Heavy_Rain                 int64
Pressure_MSL_hPa         float64
Surface_Pressure_hPa     float64
Solar_Radiation_Wm2      float64
Direct_Radiation_Wm2     float64
Diffuse_Radiation_Wm2    float64
UV_Index                 float64
Cloud_Cover_Percent        int64
Cloud_Low_Percent          int64
Cloud_Mid_Percent          int64
Cloud_High_Percent         int64
Is_Daytime                 int64
Sunshine_Seconds         float64
PM2_5_ugm3               float64
PM10_ugm3                float64
PM_Ratio                 float64
CO_ugm3                  float64
NO2_ugm3                 float64
SO2_ugm3                 float64
O3_ugm3                  float64
Dust_ugm3                float64
NH3_ugm3                 float64
AOD                      float64
US_AQI                   float64
US_AQI_PM25              float64
US_AQI_PM10              float64
US_AQI_NO2               float64
US_AQI_O3                float64
US_AQI_CO                  int64
EU_AQI                   float64
EU_AQI_PM25              float64
EU_AQI_PM10              float64
AQI_Category              object
PM25_Category_India       object
Temp_Inversion             int64
Inversion_Strength_C     float64
Festival_Period            int64
Crop_Burning_Season        int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842160 entries, 0 to 842159
Data columns (total 71 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   City                   842160 non-null  object
 1   State                  842160 non-null  object
 2   Latitude               842160 non-null  float64
 3   Longitude              842160 non-null  float64
 4   Datetime               842160 non-null  object
 5   Year                   842160 non-null  int64
 6   Month                  842160 non-null  int64
 7   Day                    842160 non-null  int64
 8   Hour                   842160 non-null  int64
 9   Day_of_Week            842160 non-null  int64
 10  Day_Name               842160 non-null  object
 11  Week_of_Year           842160 non-null  int64
 12  Is_Weekend             842160 non-null  int64
 13  Quarter                842160 non-null  int64
 14  Season                 842160 non-null  object
 15  Time_of_Day            842160 non-null  object
 16  Temp_2m_C              842160 non-null  float64
 17  Temp_80m_C             0 non-null       float64
 18  Temp_120m_C            0 non-null       float64
 19  Temp_180m_C            0 non-null       float64
 20  Humidity_Percent       842160 non-null  int64
 21  Dew_Point_C            842160 non-null  float64
 22  Humidity_Category      842160 non-null  object
 23  Wind_Speed_10m_kmh     842160 non-null  float64
 24  Wind_Speed_80m_kmh     0 non-null       float64
 25  Wind_Speed_120m_kmh    0 non-null       float64
 26  Wind_Dir_10m           842160 non-null  int64
 27  Wind_Gusts_kmh         842160 non-null  float64
 28  Wind_Category          842160 non-null  object
 29  Wind_Stagnation        842160 non-null  int64
 30  Precipitation_mm       842160 non-null  float64
 31  Rain_mm                842160 non-null  float64
 32  Is_Raining             842160 non-null  int64
 33  Heavy_Rain             842160 non-null  int64
 34  Pressure_MSL_hPa       842160 non-null  float64
 35  Surface_Pressure_hPa   842160 non-null  float64
 36  Solar_Radiation_Wm2    842160 non-null  float64
 37  Direct_Radiation_Wm2   842160 non-null  float64
 38  Diffuse_Radiation_Wm2  842160 non-null  float64
 39  UV_Index               0 non-null       float64
 40  Cloud_Cover_Percent    842160 non-null  int64
 41  Cloud_Low_Percent      842160 non-null  int64
 42  Cloud_Mid_Percent      842160 non-null  int64
 43  Cloud_High_Percent     842160 non-null  int64
 44  Is_Daytime             842160 non-null  int64
 45  Sunshine_Seconds       842160 non-null  float64
 46  PM2_5_ugm3             842160 non-null  float64
 47  PM10_ugm3              842160 non-null  float64
 48  PM_Ratio               842160 non-null  float64
 49  CO_ugm3                842160 non-null  float64
 50  NO2_ugm3               842160 non-null  float64
 51  SO2_ugm3               842160 non-null  float64
 52  O3_ugm3                842160 non-null  float64
 53  Dust_ugm3              842160 non-null  float64
 54  NH3_ugm3               0 non-null       float64
 55  AOD                    842160 non-null  float64
 56  US_AQI                 842015 non-null  float64
 57  US_AQI_PM25            842015 non-null  float64
 58  US_AQI_PM10            842015 non-null  float64
 59  US_AQI_NO2             842158 non-null  float64
 60  US_AQI_O3              842087 non-null  float64
 61  US_AQI_CO              842160 non-null  int64
 62  EU_AQI                 842015 non-null  float64
 63  EU_AQI_PM25            842015 non-null  float64
 64  EU_AQI_PM10            842015 non-null  float64
 65  AQI_Category           839644 non-null  object
 66  PM25_Category_India    842158 non-null  object
 67  Temp_Inversion         842160 non-null  int64
 68  Inversion_Strength_C   0 non-null       float64
 69  Festival_Period        842160 non-null  int64
 70  Crop_Burning_Season    842160 non-null  int64
dtypes: float64(39), int64(22), object(10)
memory usage: 456.2+ MB

In [13]:
memory_mb = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Memory Usage : {memory_mb:.2f} MB")

Memory Usage : 856.96 MB

In [18]:
df.describe(include="all")

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,Day_Name,Week_of_Year,Is_Weekend,Quarter,Season,Time_of_Day,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
count,842160,842160,842160.00,842160.00,842160,842160.00,842160.00,842160.00,842160.00,842160.00,842160,842160.00,842160.00,842160.00,842160,842160,842160.00,0.00,0.00,0.00,842160.00,842160.00,842160,842160.00,0.00,0.00,842160.00,842160.00,842160,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,0.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,842160.00,0.00,842160.00,842015.00,842015.00,842015.00,842158.00,842087.00,842160.00,842015.00,842015.00,842015.00,839644,842158,842160.00,0.00,842160.00,842160.00
unique,29,29,NaN,NaN,29040,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,4,6,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,NaN,NaN,NaN,NaN
top,Agartala,Tripura,NaN,NaN,2022-08-05 00:00:00,NaN,NaN,NaN,NaN,NaN,Friday,NaN,NaN,NaN,Monsoon,Night,NaN,NaN,NaN,NaN,NaN,NaN,Very_Humid,NaN,NaN,NaN,NaN,NaN,Moderate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate,Good,NaN,NaN,NaN,NaN
freq,29040,29040,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN,120408,NaN,NaN,NaN,294408,210540,NaN,NaN,NaN,NaN,NaN,NaN,275457,NaN,NaN,NaN,NaN,NaN,331428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385769,482562,NaN,NaN,NaN,NaN
mean,NaN,NaN,23.13,82.77,NaN,2023.72,6.80,15.74,11.50,3.00,NaN,27.77,0.29,2.60,NaN,NaN,23.63,NaN,NaN,NaN,71.32,17.15,NaN,8.12,NaN,NaN,189.34,19.28,NaN,0.06,0.20,0.20,0.20,0.00,1009.49,957.05,205.35,131.98,73.37,NaN,50.50,14.60,18.02,40.71,0.51,1393.73,34.74,56.26,0.69,450.89,16.13,13.60,80.48,23.91,NaN,0.47,96.80,91.29,44.95,7.96,45.18,4.36,62.82,58.03,48.42,NaN,NaN,0.00,NaN,0.11,0.20
std,NaN,NaN,5.54,6.94,NaN,1.00,3.41,8.77,6.92,2.00,NaN,14.85,0.45,1.11,NaN,NaN,6.86,NaN,NaN,NaN,21.36,7.08,NaN,5.08,NaN,NaN,106.03,9.99,NaN,0.24,0.92,0.92,0.40,0.06,5.70,58.39,277.57,205.53,95.01,NaN,43.41,27.64,28.83,44.57,0.50,1705.55,30.84,83.84,0.16,434.55,20.81,20.62,46.20,135.58,NaN,0.31,70.78,44.45,63.82,10.38,35.43,3.89,39.51,31.67,38.90,NaN,NaN,0.00,NaN,0.31,0.40
min,NaN,NaN,8.52,72.57,NaN,2022.00,1.00,1.00,0.00,0.00,NaN,1.00,0.00,1.00,NaN,NaN,-11.50,NaN,NaN,NaN,3.00,-29.30,NaN,0.00,NaN,NaN,0.00,0.70,NaN,0.00,0.00,0.00,0.00,0.00,979.40,767.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.10,0.10,0.07,56.00,-0.20,-0.20,-11.00,-4.00,NaN,0.00,9.00,2.00,1.00,0.00,0.00,1.00,5.00,1.00,1.00,NaN,NaN,0.00,NaN,0.00,0.00
25%,NaN,NaN,20.30,77.17,NaN,2023.00,4.00,8.00,5.75,1.00,NaN,15.00,0.00,2.00,NaN,NaN,19.60,NaN,NaN,NaN,58.00,12.10,NaN,4.30,NaN,NaN,90.00,11.50,NaN,0.00,0.00,0.00,0.00,0.00,1005.40,931.20,0.00,0.00,0.00,NaN,2.00,0.00,0.00,0.00,0.00,0.00,14.70,21.50,0.62,235.00,3.70,2.80,47.00,0.00,NaN,0.24,59.00,58.00,21.00,2.00,24.00,2.00,36.00,31.00,23.00,NaN,NaN,0.00,NaN,0.00,0.00
50%,NaN,NaN,23.83,80.95,NaN,2024.00,7.00,16.00,11.50,3.00,NaN,29.00,0.00,3.00,NaN,NaN,24.70,NaN,NaN,NaN,76.00,18.60,NaN,7.10,NaN,NaN,206.00,17.30,NaN,0.00,0.00,0.00,0.00,0.00,1009.90,977.40,9.00,0.00,8.00,NaN,47.00,0.00,4.00,12.00,1.00,0.00,25.90,39.00,0.69,333.00,9.00,6.90,73.00,2.00,NaN,0.40,84.00,81.00,36.00,4.00,35.00,3.00,62.00,61.00,40.00,NaN,NaN,0.00,NaN,0.00,0.00
75%,NaN,NaN,26.91,88.61,NaN,2025.00,10.00,23.00,17.25,5.00,NaN,41.00,1.00,4.00,NaN,NaN,28.10,NaN,NaN,NaN,89.00,23.30,NaN,10.80,NaN,NaN,280.00,25.20,NaN,0.00,0.00,0.00,0.00,0.00,1013.80,1002.80,406.00,221.00,135.00,NaN,100.00,14.00,22.00,98.00,1.00,3600.00,44.20,66.40,0.71,508.00,19.90,15.80,108.00,11.00,NaN,0.61,128.00,122.00,56.00,10.00,49.00,5.00,77.00,75.00,67.00,NaN,NaN,0.00,NaN,0.00,0.00
max,NaN,NaN,31.10,94.11,NaN,2025.00,12.00,31.00,23.00,6.00,NaN,52.00,1.00,4.00,NaN,NaN,46.40,NaN,NaN,NaN,100.00,29.80,NaN,53.10,NaN,NaN,360.00,95.80,NaN,1.00,51.70,51.70,1.00,1.00,1028.10,1021.20,1044.00,912.00,483.00,NaN,100.00,100.00,100.00,100.00,1.00,3600.00,581.10,3263.40,1.43,14504.00,336.00,424.60,930.00,5882.00,NaN,4.34,2742.00,376.00,2742.00,115.00,369.00,126.00,1179.00,301.00,1179.00,NaN,NaN,0.00,NaN,1.00,1.00

In [15]:
print("Notebook 01 Completed Successfully.")

Notebook 01 Completed Successfully.